### ISSUE TITLE
Citations in image captions not rendered

### ISSUE THREAD

**Issue by awe-hnu** [quarto-ext/lightbox#4]
Thx for contributing this extension — very helpful for my teaching material!
I often use citations within the image captions. Within the lightbox, these are shown as markdown (@Author2022ShortTitle). Is it possible to render these? Maybe related to that issue: The lightbox filter appends "fig:" to the img title.

Thank you for looking at it and possibly fixing it.

**Comment by dragonstyle** [comment]
Thanks for reporting this. I've fixed the issue with the img title. Fixing the citation in the description will be more complex since it is being embedded in an attribute of the link around the image. I'll leave this open and try to figure something out.

You can use `quarto update extension quarto-ext/lightbox` to get the latest version in any folders/projects where you're using this extension.

**Comment by awe-hnu** [comment]
Wow, you are blazing fast. Thanks a lot, Charles!
